#!/bin/bash
rm -rf dist

node node_modules/webpack/bin/webpack --config webpack.config.prod.js

cp app/index.html dist/index.html

# TODO figure out the right way to do this when you have internet...
mkdir -p dist/states/root/children/welcome/components/assets/rbb_backgrounds/
cp -r app/states/root/children/welcome/components/assets/rbb_backgrounds/ dist/states/root/children/welcome/components/assets/rbb_backgrounds/
